project:
  type: website
  output-dir: docs
website:
  title: "Reproducibility and Interactivity with R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda
format:
  html:
    theme: simplex
    # styles2.scss
    css: styles2.css
    toc: true



